import { defineConfig } from '@hey-api/openapi-ts'

// Regenerated by `make api-client` (backend/Makefile's `openapi-schema` target
// dumps openapi.json here first). Treat src/api/generated/ as a build output —
// don't hand-edit it, ARCHITECTURE §5.
export default defineConfig({
  input: './openapi.json',
  output: './src/api/generated',
  plugins: ['@hey-api/client-fetch', '@hey-api/typescript', '@hey-api/sdk'],
})
