"""transform registry and runs

Revision ID: bb9049a6c48e
Revises: 244e9746d9db
Create Date: 2026-07-24 00:02:39.506539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9049a6c48e'
down_revision: Union[str, Sequence[str], None] = '244e9746d9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transforms',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('BUILTIN', 'REMOTE', name='transform_kind'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('input_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=2000), nullable=True),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transforms_slug'), 'transforms', ['slug'], unique=True)
    op.create_table('transform_runs',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('transform_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='transform_run_status'), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('input_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_edge_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(length=4000), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['transform_id'], ['transforms.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transform_runs_case_id'), 'transform_runs', ['case_id'], unique=False)
    # ### end Alembic commands ###

    # `created_by_transform_run_id` (nodes, edges) and `actor_transform_run_id`
    # (events) existed unconstrained since the baseline migration — ProvenanceMixin
    # and Event documented them as "FK added once transform_runs exists". It exists
    # now.
    op.create_foreign_key(
        'fk_nodes_created_by_transform_run_id', 'nodes', 'transform_runs',
        ['created_by_transform_run_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_edges_created_by_transform_run_id', 'edges', 'transform_runs',
        ['created_by_transform_run_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_events_actor_transform_run_id', 'events', 'transform_runs',
        ['actor_transform_run_id'], ['id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_events_actor_transform_run_id', 'events', type_='foreignkey')
    op.drop_constraint('fk_edges_created_by_transform_run_id', 'edges', type_='foreignkey')
    op.drop_constraint('fk_nodes_created_by_transform_run_id', 'nodes', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transform_runs_case_id'), table_name='transform_runs')
    op.drop_table('transform_runs')
    op.drop_index(op.f('ix_transforms_slug'), table_name='transforms')
    op.drop_table('transforms')
    # ### end Alembic commands ###
    # autogenerate doesn't emit these: table drops don't drop the Postgres ENUM
    # types they used (same gotcha as the baseline migration's downgrade).
    sa.Enum(name='transform_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transform_run_status').drop(op.get_bind(), checkfirst=True)
